apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    app: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryhro9346.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-sync"  
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  selector:
    app: poi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP