apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    app: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryhro9346.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: openhack-dbaccess
              key: username
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: openhack-dbaccess
              key: server
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openhack-dbaccess
              key: password
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  selector:
    app: poi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP