apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 70cacc72-29d3-4c7f-a45b-b4618e4f567d  
    keyvaultName: openhack-keyvault-7589        
    objects:  |
      array:
        - |
          objectName: username
          objectAlias: SQL_USER
          objectType: secret           
        - |
          objectName: password
          objectAlias: SQL_PASSWORD
          objectType: secret
        - |
          objectName: server
          objectAlias: SQL_SERVER
          objectType: secret
    tenantId: 99c4113b-3c9e-433d-a926-173efc8db7e9 