apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
  labels:
    app: trips
spec:
  replicas: 5
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
        aadpodidbinding: api-application-identity-5e8e652c-c334-4446-ab7a-bee18646713c
    spec:
      containers:
      - name: trips
        image: registryhro9346.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        #volumeMounts:
        #- name: secrets-store01-inline
        #  mountPath: "/secrets"
        #  readOnly: true
        env:
        - name: OPENAPI_DOCS_URI
          value: http://changeme
        - name: CREDENTIAL_METHOD
          value: managed_identity
        - name: IDENTITY_CLIENT_ID
          value: 5e8e652c-c334-4446-ab7a-bee18646713c
        - name: SQL_SERVER
          value: sqlserverhro9346.database.windows.net
      #volumes:
      #  - name: secrets-store01-inline
      #    csi:
      #      driver: secrets-store.csi.k8s.io
      #      readOnly: true
      #      volumeAttributes:
      #        secretProviderClass: "azure-sync"  